// Package rebuild regenerates every projection in the tree from truth: the
// state.toml files, tree.toml, and the journals (design §2.4, §21.1).
//
// It is the repair half of the pair principle 3 rests on. `doctor` reports that
// a generated file differs from what would be written now; `rebuild` writes it.
// So the two must agree exactly about what "would be written now" means, and
// the way they are made to agree is that doctor asks this package rather than
// deriving anything of its own: Derive is the one function that turns a subject
// on disk into the bytes its files should hold, and a `stale-projection`
// finding is precisely an artifact Derive says is stale.
//
// Three properties, all of them load-bearing and all of them tested:
//
//   - **It is idempotent.** Running it twice writes nothing the second time,
//     because a file already holding the right bytes is a file nothing wrote.
//
//   - **It never reads a projection to produce one** (§21.1). The one thing it
//     reads out of a generated file is the part of it a human owns — a
//     README.md's body, an AGENTS.md's prose outside the markers, the other
//     lines of a .gitattributes (§2.1, §2.2). That is not deriving a projection
//     from a projection: every generated byte comes from truth, and those bytes
//     are the ones para is not allowed to invent.
//
//   - **ACTIVITY.md is re-derived in full, from every rotated journal file**,
//     which is the one thing write-through never does (§3.5, §21.1). This is
//     where a day that was written wrong long ago gets rewritten.
//
// It reads no clock, which is not an omission: a projection is a function of
// truth alone (§2.5 keeps everything clock-dependent out of the files), so a
// rebuild today and a rebuild tomorrow over the same tree produce the same
// bytes. If that ever stops being true, `doctor` starts reporting drift on a
// tree nobody touched, which is the failure §0.2 was written to prevent.
package rebuild

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/colchuck-ai/para/internal/address"
	"github.com/colchuck-ai/para/internal/config"
	"github.com/colchuck-ai/para/internal/journal"
	"github.com/colchuck-ai/para/internal/kindmeta"
	"github.com/colchuck-ai/para/internal/locator"
	"github.com/colchuck-ai/para/internal/mirror"
	"github.com/colchuck-ai/para/internal/paraerr"
	"github.com/colchuck-ai/para/internal/render"
	"github.com/colchuck-ai/para/internal/tree"
	"github.com/colchuck-ai/para/internal/truth"
	"github.com/colchuck-ai/para/internal/writeset"
)

// Env is what a rebuild needs from outside itself: which tree, and the resolver
// that answers §7's chained questions.
//
// There is no clock here, and the absence is the point — see the package doc.
type Env struct {
	// Root is the tree root, as an absolute OS path.
	Root string
	// Resolver answers config questions, caching each config.toml it reads.
	// One per command, as Phase 7 fixed — and it matters more here than
	// anywhere else, since a whole-tree rebuild resolves a chain per subject.
	Resolver *config.Resolver
}

// NewEnv builds an Env for one rebuild against the tree rooted at root.
func NewEnv(root string) *Env {
	return &Env{Root: root, Resolver: config.NewResolver(root)}
}

// Subject is one place that owns generated files: the tree root, a bucket or
// container, an entity, or a skill.
type Subject struct {
	Locator locator.Locator
	Kind    kindmeta.Kind
	// Dir is the subject's directory as an absolute OS path.
	Dir string
}

// Options is one rebuild: where, and whether to write.
type Options struct {
	// Scope is the container, entity, or skill to rebuild under. The empty
	// locator is the whole tree, root included.
	Scope locator.Locator
	// DryRun lists what would change and changes nothing (§21.1).
	DryRun bool
}

// Result is what a rebuild did, or would do.
type Result struct {
	// Changed names every file rewritten, in write order, as a root-relative
	// slash-separated path — the form §23 prints.
	Changed []string
	// Removed names every generated file deleted because nothing generates it
	// any more: a block-scoped file (CLAUDE.md or .gitattributes, §2.2, §6.1,
	// §9) whose block was its only content, left behind by turning its
	// `emit.*` key off and then emptied by taking the block out (R6). It is
	// separate from Changed because the two need different words — "rewrote"
	// beside a file that is gone would be a lie.
	Removed []string
	// Mirror is what happened to `.claude/skills/`, which is neither a rewrite
	// nor a plain deletion: a link, a copy, or a sweep (§6.1).
	Mirror []mirror.Change
	// Subjects is how many places were re-derived, which is the number that
	// makes "nothing to rewrite" mean "I looked" rather than "I found nothing
	// to look at".
	Subjects int
}

// Empty reports whether the rebuild did nothing at all, across all three of the
// ways it can act.
func (r Result) Empty() bool {
	return len(r.Changed) == 0 && len(r.Removed) == 0 && len(r.Mirror) == 0
}

// Run re-derives every projection under opts.Scope and writes the ones whose
// bytes differ from what is on disk.
//
// It writes as it goes rather than deriving the whole tree first, so a tree too
// big to hold in memory is still a tree that can be rebuilt. The consequence is
// stated rather than hidden: if a subject's truth will not read, the subjects
// already visited have been written and the ones after it have not. That is the
// same degraded state every crash produces — truth correct, some projections
// stale — and it has the same repair, which is to fix the truth doctor named and
// run this again (§2.4).
func Run(env *Env, opts Options) (Result, error) {
	subjects, err := Subjects(env.Root, opts.Scope)
	if err != nil {
		return Result{}, err
	}

	res := Result{Subjects: len(subjects)}

	// The skills whose own files this pass rewrites. A real run does not need
	// the list — by the time the mirror is synced the new bytes are on disk —
	// but a dry run writes nothing, so without it a copy-mode mirror of a skill
	// about to be rewritten reads as up to date and the dry run predicts less
	// work than the run does. See SyncMirror.
	var pending []string

	for _, s := range subjects {
		artifacts, err := env.Derive(s)
		if err != nil {
			return res, err
		}
		if opts.DryRun {
			id, ok := staleSkill(s, artifacts)
			if ok {
				pending = append(pending, id)
			}
		}
		wrote, removed, err := env.apply(artifacts, opts.DryRun)
		res.Changed = append(res.Changed, wrote...)
		res.Removed = append(res.Removed, removed...)
		if err != nil {
			return res, err
		}
	}

	// The mirror last. A copy-mode mirror reproduces files the subject loop has
	// just rewritten, so syncing it first would copy the versions being
	// replaced.
	//
	// It is skipped for a scope that holds no skill, because `.claude/skills/`
	// sits in no *entity's* subtree and `rebuild projects` reaching it would
	// make a scoped repair quietly tree-wide — the same rule that keeps a scoped
	// `doctor` off the derived rules (§5.3). A scope that *does* hold a skill is
	// the other case, and skipping it there was wrong: `rebuild skills.x` in
	// copy mode rewrites the skill's SKILL.md and left its mirror holding the
	// old bytes, so the command you run to repair a tree finished and `doctor`
	// stayed red.
	if len(opts.Scope) == 0 || scopeHoldsSkill(subjects) {
		changes, err := env.SyncMirror(opts.DryRun, pending, nil)
		res.Mirror = changes
		if err != nil {
			return res, err
		}
	}
	return res, nil
}

// apply brings a set of derived artifacts to disk: the stale ones are written,
// and the ones nothing generates any more are deleted. It reports both lists in
// the order they were acted on, and under dryRun it reports them and does
// nothing (§21.1).
//
// It is one function because there are two callers with one rule — the whole
// tree, through Run, and the eight CLAUDE.md files, through WriteClaudeSurface.
// Written twice, they are two places that decide whether an artifact is a write
// or a deletion, and one of them eventually stops matching Artifact.Stale.
func (e *Env) apply(artifacts []Artifact, dryRun bool) (wrote, removed []string, err error) {
	for _, a := range artifacts {
		if !a.Stale() {
			continue
		}
		abs := filepath.Join(e.Root, filepath.FromSlash(a.Path))
		if !a.Wanted {
			removed = append(removed, a.Path)
			if dryRun {
				continue
			}
			if err := os.Remove(abs); err != nil && !os.IsNotExist(err) {
				return wrote, removed, paraerr.Wrap(paraerr.KindInternal, err, fmt.Sprintf("removing %s", a.Path))
			}
			continue
		}
		wrote = append(wrote, a.Path)
		if dryRun {
			continue
		}
		// A projection, so not fsynced: it is a function of truth, and the
		// state a power failure between here and the platter would leave is the
		// one this command exists to repair (see writeset's durability).
		if err := writeset.WriteProjection(abs, a.Derived); err != nil {
			return wrote, removed, err
		}
	}
	return wrote, removed, nil
}

// scopeHoldsSkill reports whether the rebuild reached a skill, which is what
// decides whether the mirror is inside the scope or outside it.
//
// The sync it enables is still whole-directory: `rebuild skills.x` also sweeps
// an orphan mirror belonging to some other skill. That is accepted rather than
// filtered, because `.claude/skills/` is one directory that mirrors the whole of
// `.agents/skills/`, and a user who asked para to rebuild a skill has asked
// about the place both of them live.
func scopeHoldsSkill(subjects []Subject) bool {
	for _, s := range subjects {
		if s.Kind == kindmeta.KindSkill {
			return true
		}
	}
	return false
}

// staleSkill reports the id of a skill whose files *inside its own directory*
// are stale, which is what a copy-mode mirror reproduces.
//
// The skill's derived rule is deliberately not counted. It lives in
// `.agents/rules/` (§5.3), outside the skill and outside the mirror, so a run
// that rewrites only the rule changes nothing a copy holds — and saying it did
// would make a dry run over-report by exactly as much as ignoring the rest made
// it under-report.
func staleSkill(s Subject, artifacts []Artifact) (string, bool) {
	if s.Kind != kindmeta.KindSkill || len(s.Locator) != 2 {
		return "", false
	}
	dir, err := s.Locator.Path()
	if err != nil {
		return "", false
	}
	for _, a := range artifacts {
		if a.Stale() && strings.HasPrefix(a.Path, dir+"/") {
			return s.Locator[1], true
		}
	}
	return "", false
}

// Subjects returns everything under scope that owns generated files, in the
// §8.5 walk's stable order, with the tree root first when the whole tree is
// asked for.
//
// Archive stubs are not subjects: a stub is a bare ancestry placeholder with no
// .para/ and no README.md (§1.6), so there is nothing about it to generate.
//
// A scope naming nothing is an error rather than an empty rebuild, for the
// reason Phase 10 gave the scoped reads: an empty result is a wrong answer to
// an explicit question, and "para rebuild projects.acme-migation" silently
// doing nothing is the worst possible answer to a typo.
func Subjects(root string, scope locator.Locator) ([]Subject, error) {
	var out []Subject
	collect := func(n tree.Node) error {
		if n.Stub {
			return nil
		}
		out = append(out, Subject{Locator: n.Locator, Kind: n.Kind, Dir: n.Path})
		return nil
	}

	if len(scope) == 0 {
		// The root is not an entity — it is the tree (§8.1) — so the walk does
		// not visit it, and it owns four of the files §2.2 lists.
		out = append(out, Subject{Dir: root})
		if err := tree.Walk(root, collect); err != nil {
			return nil, paraerr.Wrap(paraerr.KindInternal, err, "walking the tree")
		}
		return out, nil
	}

	// Existence is asked before the subtree is walked, because Subtree answers
	// from the locator's shape and would hand back a node for a directory that
	// is not there — leaving the caller to discover it by failing to read a
	// state.toml, with an absolute path in the message.
	resolves, err := tree.Resolves(root, scope)
	if err != nil {
		return nil, err
	}
	if !resolves {
		return nil, paraerr.Newf(paraerr.KindNotFound, "%s does not exist", rebuildAddr(scope))
	}

	nodes, err := tree.Subtree(root, scope)
	if err != nil {
		return nil, err
	}
	for _, n := range nodes {
		if err := collect(n); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// Artifact is one generated file: where it belongs, the bytes truth says it
// should hold, and the bytes it holds now.
type Artifact struct {
	// Path is root-relative and slash-separated, on every platform.
	Path string
	// Derived is what truth says the file should contain.
	Derived []byte
	// Existing is what it contains now, valid only when Present.
	Existing []byte
	// Present reports whether the file is there at all. A missing generated
	// file is stale in exactly the way a wrong one is: §10 asks whether the
	// file "differs from what would be written now", and an absent file
	// differs from every possible answer.
	Present bool
	// Wanted reports whether the file should exist. It is false for residue —
	// a block-scoped file (CLAUDE.md or .gitattributes, §2.2, §9) whose block
	// was its only content, so taking the block out leaves nothing (R6) — and
	// that is the same question §10 asks, read the other way: what would be
	// written now is nothing, and a file that is there differs from nothing.
	//
	// §10's finding set is closed and has no row for residue, which is the
	// argument for folding it into `stale-projection` rather than inventing a
	// twelfth finding: the repair is `rebuild`, which is exactly what that row
	// promises.
	Wanted bool
}

// Stale reports whether the file on disk is not what truth says it should be —
// which is doctor's `stale-projection` (§10) and rebuild's whole to-do list.
func (a Artifact) Stale() bool {
	if !a.Wanted {
		return a.Present
	}
	return !a.Present || !bytes.Equal(a.Existing, a.Derived)
}

// Derive renders every file the subject owns, in render.For's order, together
// with what is on disk at each path.
//
// This is the seam the package doc names: rebuild writes what it says is stale
// and doctor reports it, so neither of them has a second opinion about what a
// projection should contain.
func (e *Env) Derive(s Subject) ([]Artifact, error) {
	in, err := e.load(s)
	if err != nil {
		return nil, err
	}

	renderers := render.For(in)
	if slices.Contains(renderers, render.Claude) {
		// CLAUDE.md's import list is the one thing a renderer needs that is not
		// in the subject's own truth (§6.1), and it is loaded only where that
		// renderer is in the set.
		if in.Rules, err = e.rules(nil); err != nil {
			return nil, err
		}
	}

	existing := map[string][]byte{}
	artifacts, err := render.Collect(in, renderers, func(path string) ([]byte, error) {
		data, err := e.read(path)
		if err != nil {
			return nil, err
		}
		if data != nil {
			existing[path] = data
		}
		return data, nil
	})
	if err != nil {
		return nil, err
	}

	out := make([]Artifact, 0, len(artifacts)+1)
	for _, a := range artifacts {
		prior, present := existing[a.Path]
		out = append(out, Artifact{Path: a.Path, Derived: a.Bytes, Existing: prior, Present: present, Wanted: true})
	}

	residue, err := e.residue(in)
	if err != nil {
		return nil, err
	}
	return append(out, residue...), nil
}

// rules is CLAUDE.md's import list: one derived rule per skill that exists,
// plus adding — the skills a caller has not written to disk yet but is about
// to, so a rehearsal of adding a skill names its own rule in the same list a
// real add would produce. RuleFilenames sorts and dedupes, so adding needs no
// particular order relative to what tree.SkillIDs already returned.
//
// It asks the skills rather than listing .agents/rules/, because a rule is a
// projection of a skill (§5.3) and §21.1 forbids deriving a projection from
// one — the listing would import a rule this same rebuild is about to delete,
// and would need a second pass to converge.
func (e *Env) rules(adding []string) ([]string, error) {
	ids, err := tree.SkillIDs(e.Root)
	if err != nil {
		return nil, err
	}
	return render.RuleFilenames(append(ids, adding...)), nil
}

// load reads everything a subject's renderers need: its truth, its whole
// journal, and its resolved config.
//
// The journal is read in full — every rotated file — because ACTIVITY.md here
// is always in full mode (§3.5, §21.1). That is the cost rebuild pays and
// write-through does not, and it is the reason the two exist.
func (e *Env) load(s Subject) (render.In, error) {
	in := render.In{Locator: s.Locator, Kind: s.Kind}

	cfg, err := e.Resolver.RenderConfig(s.Locator)
	if err != nil {
		return in, err
	}
	in.Config = cfg

	if len(s.Locator) == 0 {
		if in.Tree, err = truth.ReadTree(s.Dir); err != nil {
			return in, err
		}
	} else if in.State, err = truth.ReadState(s.Dir); err != nil {
		return in, err
	}

	if in.Events, err = journal.ReadAll(truth.LogsDir(s.Dir)); err != nil {
		return in, err
	}
	return in, nil
}

// read returns the current bytes of a root-relative path, or nil where there is
// no file there.
func (e *Env) read(path string) ([]byte, error) {
	data, err := os.ReadFile(filepath.Join(e.Root, filepath.FromSlash(path)))
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, paraerr.Wrap(paraerr.KindInternal, err, fmt.Sprintf("reading %s", path))
	}
	return data, nil
}

// rebuildAddr is loc's dotted address (R24), the same conversion every other
// package that names a Locator in an error message asks of address.String
// (internal/mutate's relocateAddr; internal/cli's entityLocatorString and
// findingLocatorString; internal/view's viewAddr; internal/doctor's
// doctorAddr; internal/query's queryAddr). The scope reaching this refusal
// was already built by the CLI's own parseAddressArgs, which resolves it
// through address.Parse before rebuild ever sees it — so the raw Locator
// string is a defensive fallback only, for the one case a scope built some
// other way (a test, a future caller) does not round-trip.
func rebuildAddr(loc locator.Locator) string {
	s, err := address.String(loc)
	if err != nil {
		return loc.String()
	}
	return s
}
